services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    working_dir: /workspace
    volumes:
      - type: bind
        source: ..
        target: /workspace
    stdin_open: true
    tty: true
